
POST http://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "name": "Test Staff",
    "email" : "teststaff@gmail.com",
    "password" : "teststaff",
    "role" : "staff"
}

###

POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
   "name": "Test Staff",
    "email" : "teststaff@gmail.com",
    "password" : "teststaff111",
    "role" : "staff"
}

###
POST http://localhost:8000/addrole HTTP/1.1
Content-Type: application/json

{
    "email" : "teststaff@gmail.com",
    "role" : "staff"
}

###
POST http://localhost:8000/forgotpassword HTTP/1.1
Content-Type: application/json

{
    "email" : "teststaff@gmail.com"
}



###
POST http://localhost:8000/resetpassword HTTP/1.1
Content-Type: application/json

{
    "email" : "teststaff@gmail.com",
    "password" : "teststaff111"
}

###
GET http://localhost:8000/staff HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RzdGFmZkBnbWFpbC5jb20iLCJyb2xlIjoic3RhZmYifQ.mBJRUQE3qZw3tmCyfzte-GmobsrYKiDGv4tqVOg8hn0"

###
GET http://localhost:8000/staff HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im9qb2F3b2x5ZGlhQGdtYWlsLmNvbSIsInJvbGUiOiJzdGFmZiJ9.M3S4pRyms3uJZAObPOqPjfx-3iAlp065lCMrPCMyVhc

###
GET http://localhost:8000/admin HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwicm9sZSI6InN0YWZmIn0.m9cAYwOAW9sqgR7kXtp2f2dnSwE2mkeICLJ53QgqLxA

###
GET http://localhost:8000/managers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwicm9sZSI6InN0YWZmIn0.m9cAYwOAW9sqgR7kXtp2f2dnSwE2mkeICLJ53QgqLxA

###
GET http://localhost:8000/logout HTTP/1.1
Content-Type: application/json
